name: TerrainAnalyzer
main: com.gmail.anthonythegu.terrainanalyzer.Main
version: 0.0.1
api-version: 1.19
author: Crayola#2819
description: Analyze your world terrain, such as average terrain height!
commands:
  terrainanalyzerconfigreload:
    description: Reloads the config
  analyzeterrain:
    description: Analyze your world terrain, such as average terrain height!